-- Problem 45: Triangular, pentagonal, and hexagonal
-- Triangle, pentagonal, and hexagonal numbers are generated by the following
-- formulae:
-- Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
-- Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
-- Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...
-- It can be verified that T[285] = P[165] = H[143] = 40755.
-- Find the next triangle number that is also pentagonal and hexagonal.
t :: Int -> Int
t n = n * (n + 1) `div` 2

p :: Int -> Int
p n = n * (3 * n - 1) `div` 2

h :: Int -> Int
h n = n * (2 * n - 1)

agonals :: (Int -> Int) -> [Int]
agonals f = map f [1 ..]

-- find duplicate values in both lists
-- note: xs and ys are assumed to be ordered
findDups :: [Int] -> [Int] -> [Int]
findDups [] ys = ys
findDups xs [] = xs
findDups (x:xs) (y:ys)
  | x < y = findDups xs (y : ys)
  | y < x = findDups (x : xs) ys
  | otherwise = x : (findDups xs ys)

p45 :: Int
p45 = (foldl1 findDups (map agonals [h,t,p])) !! 2